name: Python package

on: 
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install pipenv --upgrade
        pipenv install --dev
    - name: Publish to PyPi
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        echo "TWINE_USERNAME=${{ secrets.PYPI_USERNAME }}" > .env
        echo "TWINE_PASSWORD=${{ secrets.PYPI_PASSWORD }}" >> .env
        pipenv run python setup.py sdist bdist_wheel
        pipenv run twine upload dist/*